doc /  v0.36
CoinAlpha/hummingbot-docs pull request #206
Opened 2021-02-06 06:03 UTC by JeremyKono

2021-02-06 08:28 UTC, Nullably requested changes

2021-02-06 08:28 UTC, Nullably commented on content/strategies/liquidity-mining.mdx
> +Choose between the base and quote asset wanted to use to provide liquidity. When participating in liquidity mining, use the quote asset.
> When participating in liquidity mining, use the quote asset.

You can participate in LM with base asset as well, e.g. if you have just AVAX in your account, you can participate in AVAX-BNB,AVAX-BTC,AVAX-TRY and AVAX-USDT.

2021-02-06 08:28 UTC, Nullably commented on content/strategies/liquidity-mining.mdx
> +The liquidity mining strategy allows users to run a single strategy and earn rewards in multiple Liquidity Mining campaigns. This strategy helps users who want to participate in liquidity mining but
> This strategy helps users who want to participate in liquidity mining but doesn’t want to configure a bot with the pure market making strategy.

I wouldn't put it that way, LM strategy focuses on market making on multiple markets at the same time, whereas in PMM you can run only 1 market per bot.

2021-02-06 08:28 UTC, Nullably commented on content/strategies/liquidity-mining.mdx
> +This parameter determines for each pair the value in % for the base asset. If you set it at a certain lower value than the base %, it will only create sell orders depending on your balance.
It is to set a target of base asset balance in relation to a total asset allocation value (in percentage value). The bot will then try to achieve this target by utilising `inventory_skew` feature.

2021-02-06 08:28 UTC, Nullably commented on content/strategies/liquidity-mining.mdx
> +The spread (from mid-price) to defer the order refresh process to the next cycle. The parameter has a default value of 0.02%.
It's not spread, it's a change in order price (new vs old) in percentage value, this is to avoid replacing orders too often. The default is 0.2%

2021-02-06 08:28 UTC, Nullably commented on content/strategies/liquidity-mining.mdx
> +The multiplier used to convert average volatility to spread (`avg_volatility_period` x `volatility_to_spread_multiplier`). The predefined value is 10.
> (`avg_volatility_period` x `volatility_to_spread_multiplier`)

No, this is not correct, I don't think we need to mention this. And the predefined value is 1 not 10.

2021-02-08 00:28 UTC, vic-en requested changes

2021-02-08 00:28 UTC, vic-en commented on content/strategies/perpetual-market-making.mdx
> +If by chance, the order for `open long` gets filled, it will now open a long position, and you now have two open orders.
```suggestion
If by chance, the order for `open long` gets filled, it will now open a long position, and you now have two open orders to close the positions.
```

2021-02-08 00:28 UTC, vic-en commented on content/strategies/perpetual-market-making.mdx
> +An order would be placed to close the position immediately if the bid book’s top order’s price goes higher than the entry price of a short position or the top order of the ask book goes lower than th
```suggestion
Trailing would begin if the current price is beyond or equal to the set `ts_activation_spread`. Setting this parameter to zero would start the trailing immediately the position is opened.
```

2021-02-08 00:28 UTC, vic-en commented on content/strategies/perpetual-market-making.mdx
>  Callback rate determines the price away from peak price when trailing, beyond which a position will be closed.
```suggestion
Callback rate determines the price away from peak maximum or peak minimum price when trailing, beyond which a long position or short position will be closed respectively.
```

2021-02-08 00:28 UTC, vic-en commented on content/strategies/perpetual-market-making.mdx
> +This feature gives users the option to select the order type for closing positions when using the trailing stop feature.
```suggestion
This feature gives users the option to select the order type for closing positions which is used by the trailing stop and/or stop loss features.
```

2021-02-08 00:28 UTC, vic-en commented on content/strategies/perpetual-market-making.mdx
> +Once a profitable exit price is detected, no stop-loss order should be placed. An exception will be made for cases where the market swings swiftly to an unprofitable price within ticks or if the conf
```suggestion
Once a profitable exit price is detected, no stop-loss order should be placed. An exception could arise in cases where the market swings swiftly to an unprofitable price within ticks or if the configured trailing stop parameters are too low.
```

2021-02-08 00:28 UTC, vic-en commented on content/strategies/perpetual-market-making.mdx
> +If no exit price has been detected, a stop-loss order will be placed if loss increases to the set stop-loss spread.
```suggestion
If no exit price has been detected, a stop-loss order will be placed if loss increases to the set stop-loss spread.
![](/img/no-exit-price.png)
```

2021-02-08 00:28 UTC, vic-en commented on content/strategies/perpetual-market-making.mdx
> +Unlike `Profit_taking`, take profit feature places a limit order at a profitable price from position entry price, which is determined by the spreads for each take profit side."
```suggestion

```

2021-02-08 10:17 UTC, JeremyKono commented
Moved release notes to this branch for easier viewing.

2021-02-08 12:18 UTC, JeremyKono commented
Changes has already been made and now resolving the conversation

2021-02-09 01:02 UTC, dennisocana commented
Merging in for today's release

2021-02-09 01:02 UTC, merged