doc / probit
CoinAlpha/hummingbot-docs pull request #278
Opened 2021-03-07 16:42 UTC by JeremyKono

ProBit connector

2021-03-07 16:53 UTC, CrimsonJacket commented on content/exchange-connectors/probit.mdx
> +PROBIT EXCHANGE’S GLOBAL BRAND TRUSTED BY MILLIONS OF USERS
You dont have to CAPs this

2021-03-07 16:58 UTC, CrimsonJacket commented on content/exchange-connectors/probit.mdx
> +1. Log in to your account at https://www.probit.com/, then click your My Page > API Management (If you do not have an account, you will have to create one and enable 2FA.)
Change the URL to this `https://www.probit.com/login?locale=en-us&url=/exclusive`

2021-03-07 17:05 UTC, CrimsonJacket requested changes
Overall looks good, but it will be great to include a paragraph on the difference between ProBit Global and ProBit Korea. You can refer this link.

https://support.probit.com/hc/en-us/articles/900000921023-What-is-the-Difference-Between-ProBit-Global-ProBit-Korea

2021-03-07 17:09 UTC, CrimsonJacket commented on content/exchange-connectors/probit.mdx
> +- [Fees](https://support.probit.com/hc/en-us/articles/360017844972-Trading-Fee-Structure-at-ProBit#:~:text=Trading%20Fees,gives%20enhanced%20bonuses%20as%20well.)
Instead of a bullet point, Just do an in-text link to the fees page.
i.e.

```
Refer to ProBit's Trading Fee structure [here](https://support.probit.com/hc/en-us/articles/360017844972-Trading-Fee-Structure-at-ProBit#:~:text=Trading%20Fees,gives%20enhanced%20bonuses%20as%20well.
)
```

2021-03-07 17:09 UTC, CrimsonJacket commented on content/exchange-connectors/probit.mdx
> +Minimum order size for ProBit exchange is 1 USDT.
Include a link for this.

2021-03-08 08:00 UTC, JeremyKono commented
All requested changes have been addressed in the new commits

2021-03-08 10:22 UTC, CrimsonJacket approved these changes
LGTM 👍

2021-03-08 10:23 UTC, merged