doc/ Update Exchange Connector developer documentation
CoinAlpha/hummingbot-docs pull request #325
Opened 2021-03-31 01:54 UTC by CrimsonJacket

2021-04-01 09:22 UTC, Nullably requested changes
Well written documentation. 
Thanks a lot @CrimsonJacket  for taking the time to do this.
Some minor requested changes.

2021-04-01 09:22 UTC, Nullably commented on content/developer/overview.mdx
>  - The best way to create a connector that adheres to Hummingbot’s standard is by cloning the logic of existing connectors. We’ve done a lot of work to build our core connectors, so no need to reinven
I would add this as well

- Make sure every REST API call is done in asynchronous fashion.

2021-04-01 09:22 UTC, Nullably commented on content/developer/task1.mdx
> +Converts json snapshot data from the exchangee into standard `OrderBookMessage` format.
typo, exchangee

2021-04-01 09:22 UTC, Nullably commented on content/developer/task1.mdx
> +### `snapshot_message_from_db`
I don't think we should mention this or anything that is not typically required.

2021-04-01 09:22 UTC, Nullably commented on content/developer/task1.mdx
> +### `diff_message_from_db`
same, no need to have this in the doc.

2021-04-01 09:22 UTC, Nullably commented on content/developer/task1.mdx
> +Converts json trade data from the exchangee into standard `OrderBookMessage` format.
typo

2021-04-01 09:22 UTC, Nullably commented on content/developer/task3.mdx
> +- Verifies that the orders would be legal based on the trading rules pulled from the exchange.
~~Verifies that the orders would be legal based on the trading rules pulled from the exchange.~~
Verifies that the order satisfies exchange trading rules.

2021-04-07 06:41 UTC, CrimsonJacket commented
@Nullably Addressed your comments and made additional revisions. If it is sufficient, lets push it to `master` sooner rather than later. Seems like there's some feedback on the `#dev-*` channels wrt to updating our developer docs.

2021-04-08 03:05 UTC, Nullably approved these changes
LGTM

2021-04-12 13:31 UTC, merged

2021-04-12 13:31 UTC, dennisocana commented
Resolved a conflict due to a recent change in `Callout.js` and merged the PR.