doc / fix broken links
CoinAlpha/hummingbot-docs pull request #71
Opened 2020-11-28 06:04 UTC by rapcmia

Updated link for Houbi connectors market file in /developer/task2
Updated link for trading_rule on /developer/task3

2020-11-28 06:06 UTC, rapcmia commented
![image](https://user-images.githubusercontent.com/73840223/100495069-beb56300-3182-11eb-92b4-b58a7d5c8852.png)

![image](https://user-images.githubusercontent.com/73840223/100495079-dab90480-3182-11eb-8e68-2b9c1e0bef0f.png)

2020-11-28 22:31 UTC, dennisocana commented on content/developer/task2.mdx
> +   An example of this can be seen in [Huobi connector's market file](https://github.com/CoinAlpha/hummingbot/blob/master/hummingbot/connector/exchange/huobi/huobi_exchange.pyx) connector. The market
```suggestion
   An example of this can be seen in [Huobi connector's exchange file](https://github.com/CoinAlpha/hummingbot/blob/master/hummingbot/connector/exchange/huobi/huobi_exchange.pyx) connector. The market file shows that Huobi uses REST API alone by periodically calling the market's `_update_balances()` and `_update_order_status()` through the `_status_polling_loop()`. Also, it can be seen that no user stream files exist in Huobi's connector directory.
```

2020-11-28 22:35 UTC, dennisocana requested changes
Minor change needed. I also won't be merging this in yet. Since we now have a full list of broken links, the support team can just append all fixes to this branch.

2020-11-29 08:19 UTC, glenntomas commented
* Fix broken link, missing pictures
	- Liquid trading fees
	- Telegram chat folder 
	- AMM-ARB prerequisites 
	- v0.27.0 Contributing Guidelines
	- v0.24.0 common "how to" question
	- v0.13.0 Autostart Strategy 
	- v0.9.0 dex.watch 
		- Fix missing pictures idex_logo.png, bounty_register.png
	- v0.7.0 0x open order book relayer 
	- v0.6.0 Discovery Strategy 
	- v0.5.0 Exchange Rates 
	- v0.4.0 CLI Improvements: Import/export wallet

![qFyzqpOCqB](https://user-images.githubusercontent.com/73885708/100536891-9b5fe600-325e-11eb-9da3-c482c8cff9f3.gif)

2020-11-29 18:51 UTC, closed without merging